REGEXS = {
    'uri': r'(?P<uri>/(?!(dev|proc))([\w\.]+/)+\w+\.php)',
    'url': r'(?P<url>https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*))',
    'email_ip_address_password': r'(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+):(?P<ip_address>.+?):(?P<password>[^\s]+)',
    'email_password': r'(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+):(?P<password>[^\s]+)',
    'email': r'(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)',
    'device': r'(?P<device>/dev(/[\w\.]+)+)',
    'process': r'(?P<process>/proc(/[\w\.]+)+)',
    'ip_address_user_password': r'(?P<ip_address>(tcp/)?([0-9]{1,3}\.){3}[0-9]{1,3}((\+[0-9]{1,3})|:[0-9]{1,5})?);(?P<user>.+?);(?P<password>[^\s]+)',
    'ip_address': r'(?P<ip_address>(tcp/)?([0-9]{1,3}\.){3}[0-9]{1,3}((\+[0-9]{1,3})|:[0-9]{1,5})?)',
    'memory_address': r'(?P<memory_address>0x[a-zA-Z0-9]+((-|\s)[a-zA-Z0-9]+)?)',
    'uuid': r'(?P<uuid>\b[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-\b[0-9a-fA-F]{12}\b)',
    'memory_k': r'(?P<memory_k>\b\d+[kK][bB]?\b)',
    'disk_mb': r'(?P<disk_mb>\b\d+[mM][bB]?\b)',
    'disk_gb': r'(?P<disk_gb>\b\d+[gG][bB]?\b)',
    'clock_speed': r'(?P<clock_speed>\b\d+(\.\d+)?GHz\b)',
    # put these last
    'file': r'(?P<file>/(?!(dev|proc))([\w\.]+/)+\w+(?!\.php)(\.\w+)?)',
    'version': r'(?P<version>\b[vV]?\d+(\.\d+)+(-[0-9a-zA-Z]+)?\b)',
    'number': r'(?P<number>\b(?<=\s)\d+(?=\s)\b)',
}
